FROM python:3.11
COPY tests /client/tests
COPY requirements.txt /client
COPY client.py /client
WORKDIR /client
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD [ "python", "client.py" ]
