FROM python:3.11
# ADD client.py /client/
# ADD tests /client/
# ADD requirements.txt /client/
COPY tests /client/tests
COPY requirements.txt /client
COPY client.py /client
WORKDIR /client
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD [ "python", "client.py" ]
# RUN python client.py
